### ISSUE TITLE
[BUG] Missing fields in the csv report

### ISSUE THREAD

**Issue by zhongnansu** [opensearch-project/dashboards-reports#43] opened 2021-05-13 19:23 UTC
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Plugins**
Please list all plugins currently enabled.

**Screenshots**

**Host/Environment (please complete the following information):**

**Additional context**

--- 
I am trying to create a CSV report based on a saved search that contains fields like **@timestamp, A, B, C.D, C.E, F**, etc. But the generated file only contains **@timestamp, A, B, F** - in the report all complex fields are missing. 
In fact - the fields that mapped as _object_ in my index are missed.
Why did this happen and how can I fix it?

Kibana v 7.10.0 from docker-image "amazon/opendistro-for-elasticsearch-kibana:1.12.0"

For example:
```
   {
        "_index" : "my_index",
        "_type" : "_doc",
        "_id" : "789be064-0758-4245-8ca1-6570df3bb5a7",
        "_score" : 1.0,
        "_source" : {
          "status" : "alert",     -   simple field = string
          "issue_uid" : 123,   -   simple field = number
          "created_at" : "2020-09-21T05:02:48.000+03:00",    -   simple field = date
          "alerts_count" : 2,   -   simple field = number
          "labels" : {       -   complex field = object 
            "kubernetes" : "cluster.k8s",    -  part of complex field  -  will be missed from CSV-report
            "statefulset" : "sts1"  -  part of complex field  -  will be missed from CSV-report
          }
        }
    }

```

This issue is submitted by @uzhinskiy
https://github.com/opendistro-for-elasticsearch/kibana-reports/issues/363

**Comment by joshuali925** [comment] 2021-05-14 19:24
This issue is fixed and merged by https://github.com/opendistro-for-elasticsearch/kibana-reports/pull/361. I'm able to reproduce with `opendistro-1.13.2.0` but not the latest `dev` branch. The fix will be included in the next release

**Comment by joshuali925** [comment] 2021-05-14 20:16
Hi @uzhinskiy, sorry i was looking at the wrong thing. It seems I can't reproduce the issue you are facing. Here is what I did:

1. get docker-compose.yml from [ODFE downloads](https://opendistro.github.io/for-elasticsearch/downloads.html)
1. change version to `amazon/opendistro-for-elasticsearch:1.12.0` in yml file
1. `docker compose up`
1. in kibana devtools add this document and create index pattern
```
POST my-index/_doc
{
  "status" : "alert",
  "issue_uid" : 123,
  "created_at" : "2020-09-21T05:02:48.000+03:00",
  "alerts_count" : 2,
  "labels" : {
    "kubernetes" : "cluster.k8s",
    "statefulset" : "sts1"
  }
}
```
5. In discover create a saved search and click download CSV in reporting menu
6. Here is the result, which contains nested fields from the document
```
_index,_type,_id,_score,_source.status,_source.issue_uid,_source.created_at,_source.alerts_count,_source.labels.kubernetes,_source.labels.statefulset
my-index,_doc,TDl_bHkBYCd8AA7VQP8R,1,alert,123,09/21/2020 2:02:00 am,2,cluster.k8s,sts1
```

If you are still seeing the issue, could you let us know if you have done something different from above, and what your index mapping is? Thanks

**Closed** 2021-05-25 22:14 UTC
Labels: bug, question
